-- ============================================================
-- CyberTrack v2.0 — Supabase Schema (Full)
-- Run this in your Supabase project → SQL Editor
-- ============================================================

-- Tracking links (generated by investigator)
CREATE TABLE IF NOT EXISTS tracking_links (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug         TEXT        UNIQUE NOT NULL,
  case_id      TEXT        NOT NULL,
  label        TEXT,
  created_by   TEXT,
  created_at   TIMESTAMPTZ DEFAULT now(),
  is_active    BOOLEAN     DEFAULT true,
  disguise     TEXT        DEFAULT 'default',
  redirect_url TEXT        DEFAULT 'https://www.google.com'
);

-- All captured data per click
CREATE TABLE IF NOT EXISTS tracking_logs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  link_id         UUID        REFERENCES tracking_links(id) ON DELETE CASCADE,
  slug            TEXT,

  -- IP-based geolocation (ip-api.com — free, no key)
  ip_address      TEXT,
  isp             TEXT,
  org             TEXT,
  country         TEXT,
  country_code    TEXT,
  region          TEXT,
  city            TEXT,
  zip             TEXT,
  ip_lat          FLOAT,
  ip_lng          FLOAT,
  timezone        TEXT,
  mobile          BOOLEAN,
  proxy           BOOLEAN,
  hosting         BOOLEAN,

  -- GPS from browser Geolocation API (if granted)
  gps_lat         FLOAT,
  gps_lng         FLOAT,
  gps_accuracy    FLOAT,

  -- Device fingerprint
  user_agent      TEXT,
  browser         TEXT,
  browser_version TEXT,
  os              TEXT,
  os_version      TEXT,
  device_type     TEXT,
  device_brand    TEXT,
  device_model    TEXT,
  is_mobile       BOOLEAN,
  is_tablet       BOOLEAN,
  is_bot          BOOLEAN,

  -- Browser environment
  screen_width    INT,
  screen_height   INT,
  language        TEXT,
  platform        TEXT,
  cookie_enabled  BOOLEAN,
  do_not_track    TEXT,
  connection_type TEXT,
  referrer        TEXT,

  -- Advanced fingerprints (v2.0)
  canvas_hash          TEXT,
  webgl_vendor         TEXT,
  webgl_renderer       TEXT,
  audio_hash           TEXT,
  fonts_hash           TEXT,
  color_depth          INT,
  pixel_ratio          FLOAT,
  screen_avail_w       INT,
  screen_avail_h       INT,
  touch_support        BOOLEAN,
  max_touch_points     INT,
  hardware_concurrency INT,
  device_memory        FLOAT,
  timezone_offset      INT,
  timezone_name        TEXT,
  has_ad_blocker       BOOLEAN,
  is_incognito         BOOLEAN,
  battery_level        FLOAT,
  battery_charging     BOOLEAN,
  webrtc_local_ip      TEXT,
  plugins              TEXT,
  gpu_info             TEXT,

  clicked_at      TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE tracking_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE tracking_logs  ENABLE ROW LEVEL SECURITY;

-- Allow all reads/writes via service role (used by FastAPI backend)
DROP POLICY IF EXISTS "service_all_links" ON tracking_links;
CREATE POLICY "service_all_links" ON tracking_links FOR ALL USING (true);

DROP POLICY IF EXISTS "service_all_logs" ON tracking_logs;
CREATE POLICY "service_all_logs"  ON tracking_logs  FOR ALL USING (true);
